---

- name: Create git directory
  ansible.builtin.file:
    path: "{{ repos_folder }}"
    state: directory
    mode: '0755'

- name: Deploy repos
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "{{ repos_folder }}/{{ item | regex_replace('^.*/') }}"
  loop: "{{ repos_list }}"
  tags:
    - skip_ansible_lint
